# Generated by Django 3.0.5 on 2020-04-30 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('Rating', models.PositiveSmallIntegerField(default=1, verbose_name='Количество звезд')),
            ],
            options={
                'verbose_name': 'Отели',
                'verbose_name_plural': 'Отель',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Тип питания')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DestinationCountry', models.CharField(max_length=20, verbose_name='Страна назначения')),
                ('Departure', models.CharField(max_length=20, verbose_name='Город отправления')),
                ('DayCount', models.PositiveSmallIntegerField(default=1, verbose_name='Количество ночей')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Дата вылета')),
                ('Price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hotel', verbose_name='')),
                ('MealType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MealType', verbose_name='')),
            ],
            options={
                'verbose_name': 'Туры',
                'verbose_name_plural': 'Тур',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RoomType', verbose_name=''),
        ),
    ]
