# Generated by Django 3.0.5 on 2020-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
