# Generated by Django 3.0.5 on 2020-04-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tour_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='RoomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RoomType', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='MealType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MealType', verbose_name='Тип питания'),
        ),
    ]
