# Generated by Django 3.0.5 on 2020-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200430_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='image',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='tour',
            name='HotTour',
            field=models.BooleanField(default=False, verbose_name='Горящий тур'),
        ),
    ]
