# Generated by Django 3.0.5 on 2020-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200501_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
