# Generated by Django 3.0.5 on 2020-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200501_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Description',
            field=models.TextField(default='2', verbose_name='Описание'),
        ),
    ]
