# Generated by Django 3.0.5 on 2020-05-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_tour_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='Description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Status', verbose_name='Статус')),
            ],
        ),
    ]
